app/PicoSchool/urls.py
from django.contrib import admin
from django.urls import (
    path,
    include,
)
from django.conf.urls.static import static
from PicoSchool import settings

admin.site.site_header = "مدیریت PicoSchool"

urlpatterns = [
    path('', include('account.urls')),
    path('', include('main.urls')),
    path('manager/', include('manager.urls')),
    path('parent/', include('parent.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('poll/', include('poll.urls')),
    path('quiz/', include('quiz.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('pwa.urls')),
    path('pico-school/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

app/main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = (
    path('', views.index, name='index'),
    path('pages/events/', views.events, name='events'),
    path('pages/notices/', views.notice_box, name='notices'),
    # Student Section
    path('student/<int:pk>/detail/', views.student_detail, name="student_detail"),
    # Parent Section
    path('parent/<int:pk>/detail/', views.parent_detail, name="parent_detail"),
    # Parent Section
    path('teacher/<int:pk>/detail/', views.teacher_detail, name="teacher_detail"),
    # Class Section
    path('class/list/', views.class_list, name="class_list"),
    path('class/<int:pk>/detail/', views.class_detail, name="class_detail"),
    # Attendance Section
    path('attendance/<int:pk>/<date>/detail/', views.attendance_detail, name="attendance_detail"),
    # Home Work Section
    path('home-work/list/', views.home_work_list, name="home_work_list"),
    path('home-work/<int:pk>/detail/', views.home_work_detail, name="home_work_detail"),
    # Employment Form Section
    path('employment-form/list/', views.employment_form_list, name="employment_form_list"),
    path('employment-form/<int:pk>/detail/', views.employment_form_detail, name="employment_form_detail"),
    # News
    path('news/list/', views.news_list, name="news_list"),
)

app/quiz/urls.py
from django.urls import path

from quiz import views

app_name = "quiz"

urlpatterns = (
    path('list/', views.quiz_list, name='quiz_list'),
    path('<int:pk>/detail/', views.quiz_detail, name='quiz_detail'),
    path('detail/<int:pk>/<uuid>/', views.quiz_start, name='quiz_start'),
    path('create/', views.CreateQuiz.as_view(), name='quiz_create'),
    path('<int:pk>/update/', views.UpdateQuiz.as_view(), name='quiz_update'),
    # Questions Section
    path('questions/<int:pk>/list/', views.quiz_questions_list, name='quiz_questions_list'),
    path('questions/<int:pk>/update/', views.UpdateQuestion.as_view(), name='question_update'),
    path('questions-update/', views.update_question, name='update_question'),
    path('answers-update/', views.update_answers, name='update_answers'),
    path('create-answers/', views.create_answers, name='create_answers'),
    path('get-question/', views.get_questions, name='get_questions'),
    path('answers/', views.answers_data, name='answers_data'),
    # Result Section
    path('result/list/', views.result_list, name='result_list'),
    path('result/<pk>/<stu_pk>/detail/', views.result_detail, name='result_detail'),
    path('create-result/', views.create_result, name='create_result'),
    path('create-result-2/', views.create_result_2, name='create_result_2'),
    path('result-data/<int:pk>/', views.result_data, name='result_data'),
)

app/quiz/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.utils import timezone
from django.utils.html import format_html
from account.models import User
from extensions.utils import jalili_converter
from manager.models import (
    Classes,
    Books,
)
import uuid


class Quiz(models.Model):
    """
    Model for Main Quiz
    """
    DIFF_CHOICES = (
        ('ساده', 'ساده'),
        ('متوسط', 'متوسط'),
        ('سخت', 'سخت'),
    )

    # Fields
    uuid = models.UUIDField(
        default=uuid.uuid4,
        verbose_name='آیدی یونیک'
    )
    name = models.CharField(
        max_length=30,
        verbose_name='نام آزمون'
    )
    topic = models.CharField(
        max_length=30,
        null=True,
        blank=True,
        verbose_name='موضوع آزمون'
    )
    quiz_class = models.ForeignKey(
        Classes,
        on_delete=models.CASCADE,
        related_name='quiz_classes',
        verbose_name='کلاس آزمون'
    )
    quiz_book = models.ForeignKey(
        Books,
        on_delete=models.CASCADE,
        related_name='quiz_book',
        verbose_name='درس آزمون'
    )
    number_of_question = models.IntegerField(
        null=True,
        blank=True,
        verbose_name='تعداد سوالات'
    )
    time = models.IntegerField(
        help_text="بر اساس (دقیقه)",
        verbose_name='زمان آزمون'
    )
    show_quiz = models.BooleanField(
        default=False,
        verbose_name='نمایش سوال ها در صفحات جدا'
    )
    required_score_to_pass = models.IntegerField(
        null=True,
        blank=True,
        help_text='نمره برای قبولی بر اساس (درصد)',
        verbose_name='نمره برای قبولی'
    )
    difficulty = models.CharField(
        choices=DIFF_CHOICES,
        max_length=5,
        verbose_name='سختی آزمون'
    )
    active = models.BooleanField(
        default=False,
        verbose_name='فعال / غیرفعال'
    )
    students = models.ManyToManyField(
        User,
        related_name='quiz_student',
        blank=True,
        verbose_name='کاربران',
        limit_choices_to={'is_student': True}
    )
    created = models.DateTimeField(
        default=timezone.now,
        verbose_name='زمان ساخت'
    )
    updated = models.DateTimeField(
        auto_now=True,
        verbose_name="آخرین بروزرسانی",
    )

    # Metadata
    class Meta:
        verbose_name = "آزمون"
        verbose_name_plural = '01. آزمون ها'
        ordering = ('-created',)

    # Methods
    def __str__(self):
        return f"{self.name} - {jalili_converter(self.created)}"

    def questions(self):
        return self.question_quiz.all()

    def jdate(self):
        """
        Convert Gregorian date to Jalali
        """
        return jalili_converter(self.created)


class QuizQuestion(models.Model):
    """
    Model for main quiz questions
    """
    QUS_TYPE = (
        ('چهار گزینه ای', 'چهار گزینه ای'),
        ('تشریحی', 'تشریحی'),
    )

    # Fields
    id = models.BigIntegerField(
        unique=True,
        primary_key=True,
    )
    text = RichTextUploadingField(
        max_length=50,
        verbose_name='عنوان سوال',
    )
    quiz = models.ForeignKey(
        Quiz,
        on_delete=models.CASCADE,
        related_name='question_quiz',
        verbose_name='آزمون سوال',
    )
    question_type = models.CharField(
        choices=QUS_TYPE,
        max_length=15,
        default='چهار گزینه ای',
        verbose_name='نوع سوال'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='زمان ساخت'
    )

    # Metadata
    class Meta:
        verbose_name = "سوال"
        verbose_name_plural = '02. سوال های آزمون'

    # Methods
    def __str__(self):
        return format_html(self.text)

    def get_answers(self):
        return self.answer_question.all()


class QuizMultipleAnswers(models.Model):
    """
    Model for Answer multiple choice questions
    """

    # Fields
    text = models.CharField(
        max_length=30,
        verbose_name='عنوان پاسخ',
    )
    correct = models.BooleanField(
        default=False,
        verbose_name='پاسخ درست',
    )
    question = models.ForeignKey(
        QuizQuestion,
        on_delete=models.CASCADE,
        related_name='answer_multi_question',
        verbose_name='سوال پاسخ',
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='زمان ساخت',
    )

    # Metadata
    class Meta:
        verbose_name = "پاسخ"
        verbose_name_plural = '03. پاسخ های آزمون چهار گزینه ای'

    # Methods
    def __str__(self):
        return self.text


class QuizDescAnswers(models.Model):
    """
    Model for description Answer questions
    """

    # Fields
    text = models.TextField(
        verbose_name='متن',
    )
    question = models.ForeignKey(
        QuizQuestion,
        on_delete=models.CASCADE,
        related_name='answer_desc_question',
        verbose_name='سوال پاسخ',
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='زمان ساخت'
    )

    # Metadata
    class Meta:
        verbose_name = "پاسخ"
        verbose_name_plural = '04. پاسخ های آزمون تشریحی'

    # Methods
    def __str__(self):
        return format_html(self.question.text)


class QuizResult(models.Model):
    """
    Model for Main quiz result
    """

    # Fields
    quiz = models.ForeignKey(
        Quiz,
        on_delete=models.CASCADE,
        related_name='result_quiz',
        verbose_name='نتیجه آزمون',
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='result_user',
        verbose_name='نتیجه برای کاربر',
    )
    data = models.JSONField(
        verbose_name='اطلاعات'
    )

    # Metadata
    class Meta:
        verbose_name = "نتیجه"
        verbose_name_plural = '4. نتایج آزمون'

    # Methods
    def __str__(self):
        return "str(self.pk)"

app/quiz/forms.py
from django import forms

from quiz.models import QuizQuestion, Quiz


class CreateQuestionForm(forms.ModelForm):
    class Meta:
        model = QuizQuestion
        fields = ('text',)


class UpdateQuestionForm(forms.ModelForm):
    class Meta:
        model = QuizQuestion
        fields = ('text', )


class CreateQuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ('name', 'topic', 'quiz_class', 'quiz_book', 'time', 'show_quiz', 'difficulty')
        widgets = {
            'name': forms.TextInput(
                attrs={'placeholder': 'نام آزمون را وارد کنید'}),
            'topic': forms.TextInput(
                attrs={'placeholder': 'موضوع آزمون را وارد کنید'}),
        }


class UpdateQuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ('name', 'topic', 'quiz_class', 'quiz_book', 'active', 'time', 'show_quiz', 'difficulty', 'students')
        widgets = {
            'name': forms.TextInput(
                attrs={'placeholder': 'نام آزمون را وارد کنید'}),
            'topic': forms.TextInput(
                attrs={'placeholder': 'موضوع آزمون را وارد کنید'}),
            'students': forms.CheckboxSelectMultiple,
        }

app/quiz/templates/quiz/quiz_create.html
{% extends 'base.html' %}

{% block main %}
{% if request.resolver_match.url_name == 'quiz_create' or request.resolver_match.url_name == 'quiz_update'%}
<div class="mt-5 m-3">
    <div class="breadcrumbs-area">
        <h3>ساخت آزمون</h3>
    </div>
    <div class="card height-auto">
        <div class="card-body">
            <div class="single-info-details">
                <div class="item-content">
                    <div class="content-inline item-content">
                        <form class="new-added-form" method="post">{% csrf_token %}
                            <div class="row">
                                <div class="col-lg-12 col-12">
                                    <p class="form-group-title">اطلاعات عمومی</p>
                                </div>
                                <div class="col-xl-3 col-lg-6 col-12 form-group">
                                    <label> نام آزمون <span>*</span></label>
                                    {{ form.name }}
                                </div>
                                <div class="col-xl-3 col-lg-6 col-12 form-group">
                                    <label> موضوع <span>*</span></label>
                                    {{ form.topic }}
                                </div>
                                <div class="col-xl-3 col-lg-6 col-12 form-group">
                                    <label> کلاس <span>*</span></label>
                                    {{ form.quiz_class }}
                                </div>
                                <div class="col-xl-3 col-lg-6 col-12 form-group">
                                    <label> کتاب <span>*</span></label>
                                    {{ form.quiz_book }}
                                </div>
                                <div class="col-lg-12 col-12">
                                    <p class="form-group-title">بیشتر</p>
                                </div>
                                <div class="col-xl-2 col-lg-6 col-12 form-group">
                                    <label> زمان آزمون <span>*</span></label>
                                    {{ form.time }}
                                    <p class="help_text">{{ form.time.help_text }}</p>
                                </div>
                                <div class="col-xl-3 col-lg-6 col-12 form-group">
                                    <label> سختی <span>*</span></label>
                                    {{ form.difficulty }}
                                </div>
                                {% if request.resolver_match.url_name == "quiz_update" %}
                                <div class="col-xl-3 col-lg-6 col-12 form-group text-right">
                                    <label> فعال / غیرفعال </label>
                                    <label class="switch">
                                        {{ form.active }}
                                        <span class="slider round"></span>
                                    </label>
                                </div>
                                {% endif %}
                                <div class="col-xl-4 col-lg-6 col-12 form-group text-right">
                                    <label> نمایش سوالات در صفحات جدا <span>*</span></label>
                                    <label class="switch">
                                        {{ form.show_quiz }}
                                        <span class="slider round"></span>
                                    </label>
                                </div>
                                {% if request.resolver_match.url_name == "quiz_update" %}
                                <div class="col-xl-12 col-lg-12 col-12 form-group text-right">
                                    <div class="btn-group">
                                        {% for checkbox in form.students %}
                                        <label class="btn btn-light m-3">
                                            <div class="mt-3">
                                                {{ checkbox.tag }} {{ checkbox.choice_label }}
                                            </div>
                                        </label>
                                        {% endfor %}
                                    </div>
                                </div>
                                {% endif %}
                                <div class="col-md-12">
                                    {% if request.resolver_match.url_name == "quiz_create" %}
                                    <button class="btn btn-success" type="submit">ساخت</button>
                                    {% else %}
                                    <button class="btn btn-warning" type="submit">ویرایش</button>
                                    {% endif %}
                                    <a href="{% url 'quiz:quiz_list' %}" class="btn btn-secondary">لغو</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% elif request.resolver_match.url_name == 'question_update' %}
<div class="mt-5 m-3">
    <div class="breadcrumbs-area">
        <h3>ساخت آزمون</h3>
    </div>
    <div class="card height-auto">
        <div class="card-body">
            <div class="single-info-details">
                <div class="item-content">
                    <div class="content-inline item-content">
                        <div class="new-added-form">
                            <div class="row">
                                <div class="col-xl-3 col-lg-6 col-12 form-group">
                                    <label> نوع سوال <span>*</span></label>
                                    <select name="question_type" id="id_question_type" disabled>
                                        <option
                                                {% if question.question_type == 'چهار گزینه ای'  %}selected{% endif %}
                                        value="چهار گزینه ای" >چهار گزینه
                                        ای</option>
                                        <option {% if question.question_type == 'تشریحی' %}selected{% endif %}
                                        value="تشریحی">تشریحی</option>
                                    </select>
                                </div>
                                <div class="col-xl-9 col-lg-6 col-12 form-group"></div>
                                <div class="col-xl-12 col-lg-6 col-12 form-group">
                                    <label> عنوان سوال <span>*</span></label>
                                    {{ form.media }}
                                    {{ form.text }}
                                </div>
                                <div class="col-12" id="answers" style="display: none;">
                                    <div class="card-body my-4 add_question">
                                        <table class="add_answer">
                                            <thead>
                                            <tr>
                                                <th>عنوان پاسخ</th>
                                                <th>پاسخ درست</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for ans in question.answer_multi_question.all %}
                                            <tr>
                                                <td>
                                                    <input type="text" class="Answer" value="{{ ans }}"
                                                           id="{{ ans.id }}">
                                                </td>
                                                <td>
                                                    <input type="radio" class="CorrectAnswer"
                                                           name="correctAnswer" {% if ans.correct %}checked{%endif%}
                                                           value="{{ ans.id }}">
                                                </td>
                                            </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <button class="btn btn-success" id="edit_question"
                                        data-id="{{ request.resolver_match.kwargs.pk }}">ویرایش
                                </button>
                                <a href="{% url 'quiz:quiz_questions_list' question.quiz.pk %}"
                                   class="btn btn-secondary">برگشت</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

app/quiz/templates/quiz/quiz_detail.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
{% if request.resolver_match.url_name == "quiz_detail" %}
<div class="mt-5 m-3">
    <div class="breadcrumbs-area">
        <h3> آزمون "<b>{{ quiz.name }}</b>"</h3>
    </div>
    <div class="card height-auto">
        <div class="card-body">
            <div class="single-info-details">
                <div class="item-content">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="info-table table-responsive">
                                <div class="row">
                                    <div class="col-md-6">
                                        {% csrf_token %}
                                        <table class="table text-nowrap">
                                            <tbody>
                                            <tr>
                                                <td><h3>نام آزمون</h3></td>
                                                <td><h3><b>{{ quiz.name }}</b></h3></td>
                                            </tr>
                                            <tr>
                                                <td><h3>موضوع</h3></td>
                                                <td><h3><b>{{ quiz.topic }}</b></h3></td>
                                            </tr>
                                            <tr>
                                                <td><h3>کلاس</h3></td>
                                                <td><h3><b>{{ quiz.quiz_class }}</b></h3></td>
                                            </tr>
                                            <tr>
                                                <td><h3>کتاب</h3></td>
                                                <td><h3><b>{{ quiz.quiz_book }}</b></h3></td>
                                            </tr>
                                            <tr>
                                                <td><h3>وضعیت</h3></td>
                                                <td>
                                                    <h3 class="badge badge-{% if quiz.active %}success{% else %}danger{% endif %}">
                                                        {% if quiz.active %}فعال{% else %}غیر فعال{% endif %}
                                                    </h3>
                                                </td>
                                            </tr>

                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="col-md-6">
                                        <table class="table text-nowrap">
                                            <tbody>
                                            <tr>
                                                <td><h3>نمایش سوالات در صفحات جدا؟</h3></td>
                                                <td><h3><b>
                                                    {% if quiz.show_quiz %}
                                                    بله
                                                    {% else %}
                                                    خیر
                                                    {% endif %}
                                                </b></h3></td>
                                            </tr>
                                            <tr>
                                                <td><h3>زمان آزمون</h3></td>
                                                <td><h3><b>{{ quiz.time }} دقیقه</b></h3></td>
                                            </tr>
                                            <tr>
                                                <td><h3>سختی</h3></td>
                                                <td>
                                                    <h3 class="badge badge-{% if quiz.difficulty == 'آسان' %}success{% elif quiz.difficulty == 'متوسط' %}warning{% elif quiz.difficulty == 'سخت' %}danger{% endif %}">
                                                        {{ quiz.difficulty }}
                                                    </h3>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                        <h3>دانش آموزانی که شرکت کرده اند:</h3>
                                        {% for student in quiz.students.all %}
                                            <b>{{ student }}</b>،
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% if request.user.is_superuser or request.user.is_manager %}
                        <div class="col-md-12">
                            <hr>
                        </div>
                        <div class="col-md-12">
                            <a href="{% url 'quiz:quiz_questions_list' quiz.pk %}" class="btn btn-info w-100">
                                لیست سوالات آزمون
                            </a>
                        </div>
                        <div class="col-md-12">
                            <hr>
                        </div>
                        {% endif %}
                        <div class="col-md-12 mt-3">
                            <a href="{% url 'quiz:quiz_list' %}" class="btn btn-secondary">برگشت</a>
                            {% if request.user.is_superuser or request.user.is_manager %}
                            <a href="{% url 'quiz:quiz_update' quiz.pk %}" class="btn btn-warning">ویرایش</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% elif request.resolver_match.url_name == "result_detail" %}
<input type="hidden" class="d-none" id="result_pk" data-pk="{{ request.resolver_match.kwargs.pk }}">
<div class="mt-5 m-3" id="printResult">
    <style>
    @media print {
    .noPrint {
        display: none;
    }
    .w-100-print{
        width: 100%;
    }
}
</style>
    <div class="breadcrumbs-area">
        <h3> نتیجه آزمون " <b>{{ result.quiz.name }}</b>" برای دانش آموز <b>"{{ result.user }}"</b> </h3>
    </div>
    <div class="card height-auto">
        <div class="card-body">
            <div class="single-info-details">
                <div class="item-content">
                    {% for qus in questions %}
                    <input type="hidden" class="d-none" value="{{ qus.id }}" data-text='{{ qus }}' name="qus_id" >
                    <div class="card-body my-4">
                        <div class="row">
                            <div class="col-md-12">
                                <h3>{{ qus }}</h3><span class="text-secondary" id="not{{ qus.id }}" style="display: none;">(پاسخ نداده)</span>
                                {% if qus.question_type == "تشریحی" %}
                                 <input type="hidden" class="d-none" value="{{ qus.id }}" name="qus_id">
                                    {% for ans in qus.answer_desc_question.all %}
                                    <textarea class="form-control w-100 text-qus" id="box{{ qus.id }}"
                                                      cols="30" rows="10" disabled></textarea>
                                    {% endfor %}
                                {% elif qus.question_type == "چهار گزینه ای" %}
                                <input type="hidden" class="d-none" id="user_role" data-is_superuser="{{ request.user.is_superuser }}"
                                data-is_teacher="{{ request.user.is_teacher }}">
                                {% for ans in qus.answer_multi_question.all %}
                                <input type="hidden" class="d-none" id="{{ ans.id }}" value="{% if ans.correct %}{{ ans.pk }}{% endif %}">
                                <input type="hidden" class="d-none" name="ans_id" value="{{ ans.id }}">
                                <div class="d-block mt-2 ">
                                    <input type="radio" value="{{ ans.text }}"
                                           id="{{ qus.pk }}-{{ ans.pk }}" class="answer"
                                           data-pk="{{ ans.pk }}"
                                           data-correct="{% if ans.correct %}{{ ans.pk }}{% endif %}"
                                           style="width: 18px; height: 18px;"
                                            disabled>
                                    <label for="{{ qus.pk }}-{{ ans.pk }}" id="lbl{{ ans.pk }}" class="h3">{{ ans.text }}</label>
                                </div>
                                {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <a href="{% url 'quiz:result_list' %}" class="btn btn-secondary noPrint">برگشت</a>
            {% if request.user.is_superuser or request.user.is_manager or request.user.is_teacher %}
            <button class="btn btn-warning noPrint" id="printResultBtn"> <i class="fas fa-print"></i> چاپ سوالات</button>
            {% endif %}
        </div>
    </div>
</div>
{% endif %}
{% endblock %}
{% block js_files %}<script src='{% static "quiz/results.js" %}'></script>{% endblock %}